---

# Install Apache server
- hosts: all
  tasks:
  
  # required to prevent build fails
  - name: update the cache
    apt:
      update_cache: yes

  - name: Install Apache2
    apt:
      name: apache2
      state: present

  - name: Set timezone to Africa/Lagos (WAT)
    timezone:
      name: Africa/Lagos

  - name: Display hostname and set the Timezone
    shell: echo "<h1>This server has the IP $(hostname -f) with date $(date)</h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted